container:
  type: ColumnPanel
  properties:
    role: tonal-card
    background: theme:surface-variant
    border: 1
    padding: 16
    spacing_above: small
    spacing_below: small
components:
- type: Label
  properties:
    text: {title}
    role: title
    bold: true
    foreground: theme:on-surface-variant
- type: Label
  properties:
    text: {description}
    role: body
    italic: true
    foreground: theme:on-surface-variant
