components:
- components:
  - data_bindings:
    - {code: 'self.item[''title'']', property: text, writeback: false}
    layout_properties: {grid_position: 'NQMVIL,TOHNPI'}
    name: lbl_title
    properties: {role: task-title}
    type: Label
  - data_bindings:
    - {code: 'self.item[''description'']', property: text, writeback: false}
    layout_properties: {grid_position: 'TXMJDR,LTVEPH'}
    name: lbl_desc
    properties: {role: task-description}
    type: Label
  data_bindings: []
  layout_properties: {grid_position: 'KTYKLV,FKYBLD'}
  name: column_panel_1
  properties: {role: input-container}
  type: ColumnPanel
container: {type: ColumnPanel}
is_package: true
