components:
- components:
  - data_bindings:
    - {code: 'self.item[''title'']', property: text, writeback: false}
    layout_properties: {grid_position: 'NQMVIL,TOHNPI'}
    name: lbl_title
    properties: {role: headline}
    type: Label
  - data_bindings:
    - {code: 'self.item[''description'']', property: text, writeback: false}
    layout_properties: {grid_position: 'TXMJDR,LTVEPH'}
    name: lbl_desc
    properties: {}
    type: Label
  layout_properties: {grid_position: 'KTYKLV,FKYBLD'}
  name: column_panel_1
  properties: {role: outlined-card}
  type: ColumnPanel
container: {type: ColumnPanel}
is_package: true
