components:
- properties:
    bold: true
    foreground: theme:on-surface-variant
    role: title
    text: {title: null}
  type: Label
- properties:
    foreground: theme:on-surface-variant
    italic: true
    role: body
    text: {description: null}
  type: Label
container:
  properties: {background: 'theme:surface-variant', border: 1, padding: 16, role: tonal-card, spacing_above: small, spacing_below: small}
  type: ColumnPanel
is_package: true
