components:
- components:
  - data_bindings:
    - {code: 'self.item[''title'']', property: text, writeback: false}
    layout_properties: {grid_position: 'HLJTRK,YCFNPA'}
    name: lbl_task_title
    properties: {}
    type: form:dep_s2fhmt4crkahq5:_Components.Heading
  - data_bindings:
    - {code: 'self.item[''description'']', property: text, writeback: false}
    layout_properties: {grid_position: 'GDGLWF,MLAESF'}
    name: lbl_task_description
    properties: {}
    type: form:dep_s2fhmt4crkahq5:_Components.Text
  layout_properties: {grid_position: 'KTYKLV,FKYBLD'}
  name: column_panel_1
  properties: {role: outlined-card}
  type: ColumnPanel
container: {type: ColumnPanel}
is_package: true
